
name: Update assets.json

on:
  push:
    paths:
      - 'assets/**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install gray-matter

      - name: Generate assets.json
        run: |
          mkdir -p public
          echo '[]' > public/assets.json
          node scripts/generateAssets.js

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/assets.json
          git commit -m "Update assets.json" || echo "No changes to commit"
          git push
